/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import com.darchan.elements.iface.IBus;
import com.darchan.elements.iface.IClock;
import com.darchan.elements.impl.Bus;
import com.darchan.elements.impl.Clock;
import com.darchan.elements.impl.SignalNameDecorator;
import com.darchan.elements.impl.comp.Inverter;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    	
    	//create high source
//    	ISignal src = new SignalNameDecorator(new HighSource(), "SRC");
    	IClock src = new Clock();
    	IBus inputBus = new Bus(src);
    	
    	//create inverter
    	Inverter inverter = new Inverter(inputBus);
    	
    	for (int i=0; i<100; i++) {
    		System.out.print(new SignalNameDecorator(src, "CLOCK"));
        	System.out.print(new SignalNameDecorator(inverter.getOutputBus().getSignals().get(0), "OUT"));
        	System.out.println();
        	src.tick();
    	}
    	
    }
}
